repos:
  # Using this fork because of it's support for env files.
  - repo: https://github.com/jeffqumata/pre-commit-hook-ensure-sops
    rev: v1.4
  # - repo: https://github.com/yuvipanda/pre-commit-hook-ensure-sops
  #   rev: v1.1
    hooks:
      - id: sops-encryption
        # Uncomment to exclude all markdown files from encryption
        # exclude: *.\.md
